
function(create_stage)
  set(OUTPUT_PREFIX "${CMAKE_BINARY_DIR}/artifacts")
  foreach(OUTPUTCONFIG ${CMAKE_CONFIGURATION_TYPES})
        string(TOUPPER _${OUTPUTCONFIG} OUTPUTCONFIG_UPPER)
        list(APPEND FIXUP_DEFINES " -D CMAKE_ARCHIVE_OUTPUT_DIRECTORY${OUTPUTCONFIG_UPPER}=${OUTPUT_PREFIX}/${OUTPUTCONFIG}/lib")
        list(APPEND FIXUP_DEFINES " -D CMAKE_LIBRARY_OUTPUT_DIRECTORY${OUTPUTCONFIG_UPPER}=${OUTPUT_PREFIX}/${OUTPUTCONFIG}/lib")
        list(APPEND FIXUP_DEFINES " -D CMAKE_RUNTIME_OUTPUT_DIRECTORY${OUTPUTCONFIG_UPPER}=${OUTPUT_PREFIX}/${OUTPUTCONFIG}/bin")
  endforeach()
  string(REPLACE ";" "\;" pp "${CMAKE_PREFIX_PATH}")
  add_custom_target(create_distribution_bundle
    ${CMAKE_COMMAND} 
    ${FIXUP_DEFINES}
    -D ROOT_PROJECT_NAME="Biogears"
    -D PROJECT_SOURCE_DIR=${PROJECT_SOURCE_DIR}
    -D CMAKE_BINARY_DIR=${CMAKE_BINARY_DIR}
    -D CMAKE_PREFIX_PATH=${pp}
    -D CMAKE_EXECUTABLE_SUFFIX=${CMAKE_EXECUTABLE_SUFFIX}
    -D CMAKE_ARCHIVE_OUTPUT_DIRECTORY=${OUTPUT_PREFIX}/lib
    -D CMAKE_LIBRARY_OUTPUT_DIRECTORY=${OUTPUT_PREFIX}/lib
    -D CMAKE_RUNTIME_OUTPUT_DIRECTORY=${OUTPUT_PREFIX}/bin
    -D CMAKE_INSTALL_CONFIG_NAME=$<CONFIG> 
    -P "${CMAKE_SOURCE_DIR}/cmake/fixup_bundle.cmake"
    VERBATIM
    )
  set_target_properties(create_distribution_bundle
      PROPERTIES
      FOLDER ""
      PROJECT_LABEL "create_distribution_bundle"
  )
endfunction() 
